---
#
# EVPN services
#
l3_vnis:
  - vrf: Production
    vlan_id: 3000
    rd: auto
    vni: 103000
    state: present

l2_vnis:
  - vni: 101000
    vlan_id: 1000
    vrf: Production
    mcast: 239.239.239.1
    descr: K8s
    state: present
  - vni: 101001
    vlan_id: 1001
    vrf: Production
    mcast: 239.239.239.2
    descr: VDI
    state: present
  - vni: 101002
    vlan_id: 1002
    vrf: Production
    mcast: 239.239.239.3
    descr: Bare metal
    state: present
